# pip install progpt

import tkinter as tk
from tkinter import filedialog
from ProGPT import Generative

# Function to interact with ChatGPT based on the input text
def chat_with_gpt():
    file_path = entry_file_path.get()
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            first_50_words = ' '.join(content.split()[:50])
            chatgpt_output = bot.prompt(first_50_words + " Is this generated by you")
            output_text.config(state='normal')
            output_text.delete('1.0', tk.END)
            output_text.insert(tk.END, chatgpt_output)
            output_text.config(state='disabled')
    except FileNotFoundError:
        output_text.config(state='normal')
        output_text.delete('1.0', tk.END)
        output_text.insert(tk.END, f"File not found at path
                           : {file_path}")
        output_text.config(state='disabled')
    except Exception as e:
        output_text.config(state='normal')
        output_text.delete('1.0', tk.END)
        output_text.insert(tk.END, f"An error occurred: {e}")
        output_text.config(state='disabled')

# Initialize ChatGPT
access_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJwYW5kZXJkOEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJwb2lkIjoib3JnLTFxSTVCTHN3T29RMnpUR2FZRnhJenJSbiIsInVzZXJfaWQiOiJ1c2VyLXJ4WjllNGg2QVpUa2ptQlVSbzNhdnpaTiJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDU5OTY0MDcwOTExNzk4NDQ3MzMiLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzA3NjY3OTExLCJleHAiOjE3MDg1MzE5MTEsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb3JnYW5pemF0aW9uLndyaXRlIG9mZmxpbmVfYWNjZXNzIn0.dPo4od7g-HoLrd7ICozcIECz_N2-hBHSM63IYcYyctRTCjVrlhHGQQSQgvowOOowh1voYcarPl5rupP2-akBze8G9ir708VBjhTh5syUit3TztjSLfB0ns7f5tGD3gUSG9gs_7BtijBOSJV007pZIWkoHa55BTpgBh29ijKt_IOiSHKHdU88bD1UB5UsBH4dNsdMDSdbf_NqUQG-WU9SshXzxMAhOKkUlv2movyb5X_yP16vy2ebzFrY7caYttumTBRnLQDQyhQXeVo9QyGCmiZWjflK98wlKLzQWf55G2aCeP1sDf_AsYihJvhq9U5dO7bRcnpTVeLHBR4c27CKUw"
bot = Generative(access_token)

# Create the main application window
app = tk.Tk()
app.title("ChatGPT Text Interaction")

# Create and place widgets
label_file_path = tk.Label(app, text="Enter file path:")
label_file_path.grid(row=0, column=0, padx=10, pady=10)

entry_file_path = tk.Entry(app, width=50)
entry_file_path.grid(row=0, column=1, padx=10, pady=10)

button_browse = tk.Button(app, text="Browse", command=lambda: entry_file_path.insert(tk.END, filedialog.askopenfilename()))
button_browse.grid(row=0, column=2, padx=10, pady=10)

button_chat = tk.Button(app, text="Chat with GPT", command=chat_with_gpt)
button_chat.grid(row=1, column=0, columnspan=3, padx=10, pady=10)

output_text = tk.Text(app, height=10, width=60)
output_text.grid(row=2, column=0, columnspan=3, padx=10, pady=10)
output_text.config(state='disabled')

# Run the application
app.mainloop()
